name: trajectory
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.8
    - pip>=18.0
    - conda>=4.5.9
    - patchelf=0.9
    - pip:
        - -f https://download.pytorch.org/whl/torch_stable.html
        - numpy==1.19.5
        - gym==0.18.0
        - mujoco-py>=2.1,<2.2
        - matplotlib==3.3.4
        - torch==1.8.1+cu101
        - torchvision==0.9.1+cu101
        - typed-argument-parser
        - scikit-image==0.17.2
        - scikit-video==1.1.11
        - gitpython
        - wandb
        - omegaconf
        - stable_baselines3
