checkpoints_path: "pretrained/medium/halfcheetah"
model_name: "model_last.pt"

max_steps: 600
num_episodes: 5
beam_context: 10
beam_steps: 5
beam_width: 32
plan_every: 1
sample_expand: 2
k_act: null
k_obs: 1
k_reward: 1
temperature: 1.0
discount: 0.99
vectorized: false

finetune: true
finetune_ratio: 0.1
finetune_epochs: 10
finetune_lr: 0.00006
render_path: null  # WARN: only for not vectorized
